# Generated by Django 6.0.2 on 2026-03-04 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_gedicht', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestellung',
            options={'verbose_name': 'Bestellung', 'verbose_name_plural': 'Bestellungen'},
        ),
        migrations.AddField(
            model_name='bestellung',
            name='zeitpunkt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
