# Generated by Django 5.2.12 on 2026-03-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_gedicht', '0002_alter_bestellung_options_bestellung_zeitpunkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellung',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
